version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    container_name: node_app
    restart: always
    ports:
      - 4000:8080
    command: bash -c /app/start.sh
    env_file: .env